export const DISPLAY_NEXT_IMAGE = "DISPLAY_NEXT_IMAGE";
export const DISPLAY_PREVIOUS_IMAGE = "DISPLAY_PREVIOUS_IMAGE";
export const DISPLAY_CHOSEN_IMAGE = "DISPLAY_CHOSEN_IMAGE";
export const CHANGE_STYLE = "CHANGE_STYLE";
export const SELECT_SIZE = "SELECT_SIZE";
export const ADD_TO_BAG = "ADD_TO_BAG";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
