export const DISPLAY_NEXT_IMAGE = "DISPLAY_NEXT_IMAGE";
export const SHOW_REVIEWS = "SHOW_REVIEWS";
export const CHANGE_STYLE = "CHANGE_STYLE";
export const SELECT_SIZE = "SELECT_SIZE";
export const SELECT_QUANTITY = "SELECT_QUANTITY";
export const ADD_TO_BAG = "ADD_TO_BAG";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
