export const CHANGE_RATING_FILTER = "CHANGE_RATING_FILTER";
export const CHANGE_SORTING_CRITERIA = "CHANGE_SORTING_CRITERIA";
export const ADD_REVIEW_HELPFUL = "ADD_REVIEW_HELPFUL";
export const SHOW_MORE_REVIEWS = "SHOW_MORE_REVIEWS";
export const REPORT_REVIEW = "REPORT_REVIEW";
export const SUBMIT_REVIEW = "SUBMIT_REVIEW";
