export const CHANGE_RATING_FILTER = 'CHANGE_RATING_FILTER';
export const CHANGE_SORTING_CRITERIA = 'CHANGE_SORTING_CRITERIA';
export const SHOW_MORE_REVIEWS = 'SHOW_MORE_REVIEWS';
export const GET_AVG_RATING = 'GET_AVG_RATING';
export const GET_REVIEWS_DATA = 'GET_REVIEWS_DATA';
